name: 每日 W 底策略回测并推送 Telegram

on:
  schedule:
   # 台湾时间每天 08:00 → UTC 00:00
    - cron: '30 01 * * *'
    # 台湾时间每天 12:00 → UTC 04:00
    - cron: '0 04 * * *'
  
  workflow_dispatch:

jobs:
  backtest-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行 W 底回测脚本并推送 Telegram
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:   ${{ secrets.CHAT_ID }}
        run: |
          python w_pattern_backtest.py
